### ISSUE TITLE
Verkehrsmodell aus XML-Datei erzeugen

### ISSUE THREAD

**Issue by sro1993** [sereGkaluv/Roundabout-Simulation-Library#35]

**Comment by DaGrisa** [comment]
branch feature/xml-structure

**Comment by DaGrisa** [comment]
tracks, intersection model generieren (plus verbindung zu trafsim intersection) fehlt noch

**Comment by DaGrisa** [comment]
umbau von @sro1993 integrieren:

**Comment by sereGkaluv** [comment]
solved in ui_roundabout_south branch
