### ISSUE TITLE
Car

### ISSUE THREAD

**Issue by DaGrisa** [sereGkaluv/Roundabout-Simulation-Library#9]
![entitaten-2](https://user-images.githubusercontent.com/11348169/33384506-8221f054-d526-11e7-8edb-0b873c6de1af.png)

**Comment by DaGrisa** [comment]
test missing

**Comment by DaGrisa** [comment]
check noch falsch ```if(lastUpdateTime >= 0)```, da im konstruktor 0 gesetzt wird

**Comment by DaGrisa** [comment]
new methods to implement from "Events" PR

**Comment by plitvica** [comment]
done
